#ifndef _ANALYZE_ERROR_H_
#define _ANALYZE_ERROR_H_

#include <glib.h>

#define ANALYZE_ERROR (analyze_error_quark())

typedef enum {
  ANALYZE_ERROR_GENERIC = 0,
  ANALYZE_ERROR_ILLEGAL_REQUEST,
  ANALYZE_ERROR_ILLEGAL_ARGUMENT,
  ANALYZE_ERROR_MISSING_ARGUMENT,
  ANALYZE_ERROR_DIMENSIONS,
  ANALYZE_ERROR_NOT_FOUND,
  ANALYZE_ERROR_GET_RESOLUTION,
  ANALYZE_ERROR_CONVERT,
  ANALYZE_ERROR_CAPTURE
} ANALYZE_ERROR_CODE;

GQuark
analyze_error_quark(void);

#endif /* _ANALYZE_ERROR_H_ */
